# Create two Dockerfile for services with slight differences between dev and prod env (e.g. xdebug enabled in dev env)
dev: true
prod: true

php:
  version: 5.6.21
  packages: [] # Additional packages
  php_ini: {} # Additional php.ini config
  php_fpm: {} # Additional php-fpm.ini config
  timezone: Europe/Paris
  src_dir: /usr/src/app
  exts:
    gd: '*'
    gmp: '*'
    intl: '*'
    mbstring: '*'
    pcntl: '*'
    memcache: '*'
    amqp: '1.4.0'
    sundown: '0.3.11'
    exif: '*'
    pdo_mysql: '*'
    openssl: '*'
  extra_steps:
    pre_apt: []
    pre_exts: []
    pre_config: []
    pre_composer: []
    pre_copy: []

mysql:
  verson: '5.7.10'
  sql_mode: [STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION]

memcached: true

elasticsearch:
  version: 2.1.2

rabbitmq:
  version: 3.6.1

# Issue #1: [RFC] Declarative format
# Issue #2: [RFC] Support for dev/prod environment
# Issue #3: [RFC] composer.json
# Issue #4: [RFC] Multiple services (mysql, rabbitmq, ...) + depends_on
# Issue #5: [RFC] Build container
